### ISSUE TITLE
Comply with the MIT license

### ISSUE THREAD

**Issue by lpinca** [yuhao423/YuFlux#28]
The code in this repository is mostly copied from https://github.com/websockets/ws which is released under the MIT license. Please add a copyright notice as per the license requirements.

```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

Thank you.

**Comment by yuhao423** [comment]
Sorry about that. I will fixed it in these days. By the way,If has any `ws` issues ,I'd like to contribute.

**Comment by lpinca** [comment]
You can use

```
git --no-pager show -s --format='%an <%ae>' <gitsha>
```

to get it. Replace `<gitsha>` with the sha of any commit I made on GitHub.

**Comment by yuhao423** [comment]
Thanks, Keep in touch.
